#!/usr/bin/python -u
"""
Libvirt Error listing Library
"""

import libvirt

ERROR = {
libvirt.VIR_ERR_OK: "Successful",
libvirt.VIR_ERR_INTERNAL_ERROR: "Internal error",
libvirt.VIR_ERR_NO_MEMORY: "Memory allocation failure",
libvirt.VIR_ERR_NO_SUPPORT: "No support for this function",
libvirt.VIR_ERR_UNKNOWN_HOST: "Could not resolve hostname",
libvirt.VIR_ERR_NO_CONNECT: "Can't connect to hypervisor",
libvirt.VIR_ERR_INVALID_CONN: "Invalid connection object",
libvirt.VIR_ERR_INVALID_DOMAIN: "Invalid domain object",
libvirt.VIR_ERR_INVALID_ARG: "Invalid function argument",
libvirt.VIR_ERR_OPERATION_FAILED: "A command to hypervisor failed",
libvirt.VIR_ERR_GET_FAILED: "A HTTP GET command to failed",
libvirt.VIR_ERR_POST_FAILED: "A HTTP POST command to failed",
libvirt.VIR_ERR_HTTP_ERROR: "Unexpected HTTP error code",
libvirt.VIR_ERR_SEXPR_SERIAL: "Failure to serialize an S-Expr",
libvirt.VIR_ERR_NO_XEN: "Could not open Xen hypervisor control",
libvirt.VIR_ERR_XEN_CALL: "Failure doing an hypervisor call",
libvirt.VIR_ERR_OS_TYPE: "Unknown OS type",
libvirt.VIR_ERR_NO_KERNEL: "Missing kernel information",
libvirt.VIR_ERR_NO_ROOT: "Missing root device information",
libvirt.VIR_ERR_NO_SOURCE: "Missing source device information",
libvirt.VIR_ERR_NO_TARGET: "Missing target device information",
libvirt.VIR_ERR_NO_NAME: "Missing domain name information",
libvirt.VIR_ERR_NO_OS: "Missing domain OS information",
libvirt.VIR_ERR_NO_DEVICE: "Missing domain devices information",
libvirt.VIR_ERR_NO_XENSTORE: "Could not open Xen Store control",
libvirt.VIR_ERR_DRIVER_FULL: "Too many drivers registered",
libvirt.VIR_ERR_CALL_FAILED: "Not supported by the drivers (DEPRECATED)",
libvirt.VIR_ERR_XML_ERROR: "An XML description is not well formed or broken",
libvirt.VIR_ERR_DOM_EXIST: "The domain already exist",
libvirt.VIR_ERR_OPERATION_DENIED: "Operation forbidden on read-only connections",
libvirt.VIR_ERR_OPEN_FAILED: "Failed to open a conf file",
libvirt.VIR_ERR_READ_FAILED: "Failed to read a conf file",
libvirt.VIR_ERR_PARSE_FAILED: "Failed to parse a conf file",
libvirt.VIR_ERR_CONF_SYNTAX: "Failed to parse the syntax of a conf file",
libvirt.VIR_ERR_WRITE_FAILED: "Failed to write a conf file",
libvirt.VIR_ERR_XML_DETAIL: "Detail of an XML error",
libvirt.VIR_ERR_INVALID_NETWORK: "Invalid network object",
libvirt.VIR_ERR_NETWORK_EXIST: "The network already exist",
libvirt.VIR_ERR_SYSTEM_ERROR: "General system call failure",
libvirt.VIR_ERR_RPC: "Some sort of RPC error",
libvirt.VIR_ERR_GNUTLS_ERROR: "Error from a GNUTLS call",
libvirt.VIR_WAR_NO_NETWORK: "Failed to start network",
libvirt.VIR_ERR_NO_DOMAIN: "Domain not found or unexpectedly disappeared",
libvirt.VIR_ERR_NO_NETWORK: "Network not found",
libvirt.VIR_ERR_INVALID_MAC: "Invalid MAC address",
libvirt.VIR_ERR_AUTH_FAILED: "Authentication failed",
libvirt.VIR_ERR_INVALID_STORAGE_POOL: "Invalid storage pool object",
libvirt.VIR_ERR_INVALID_STORAGE_VOL: "Invalid storage vol object",
libvirt.VIR_WAR_NO_STORAGE: "Failed to start storage",
libvirt.VIR_ERR_NO_STORAGE_POOL: "Storage pool not found",
libvirt.VIR_ERR_NO_STORAGE_VOL: "Storage volume not found",
libvirt.VIR_WAR_NO_NODE: "Failed to start node driver",
libvirt.VIR_ERR_INVALID_NODE_DEVICE: "Invalid node device object",
libvirt.VIR_ERR_NO_NODE_DEVICE: "Node device not found",
libvirt.VIR_ERR_NO_SECURITY_MODEL: "Security model not found",
libvirt.VIR_ERR_OPERATION_INVALID: "Operation is not applicable at this time",
libvirt.VIR_WAR_NO_INTERFACE: "Failed to start interface driver",
libvirt.VIR_ERR_NO_INTERFACE: "Interface driver not running",
libvirt.VIR_ERR_INVALID_INTERFACE: "Invalid interface object",
libvirt.VIR_ERR_MULTIPLE_INTERFACES: "More than one matching interface found",
libvirt.VIR_WAR_NO_NWFILTER: "Failed to start nwfilter driver",
libvirt.VIR_ERR_INVALID_NWFILTER: "Invalid nwfilter object",
libvirt.VIR_ERR_NO_NWFILTER: "NW filter pool not found",
libvirt.VIR_ERR_BUILD_FIREWALL: "NW filter pool not found",
libvirt.VIR_WAR_NO_SECRET: "Failed to start secret storage",
libvirt.VIR_ERR_INVALID_SECRET: "Invalid secret",
libvirt.VIR_ERR_NO_SECRET: "Secret not found",
libvirt.VIR_ERR_CONFIG_UNSUPPORTED: "Unsupported configuration construct",
libvirt.VIR_ERR_OPERATION_TIMEOUT: "Timeout occurred during operation",
libvirt.VIR_ERR_MIGRATE_PERSIST_FAILED: "A migration worked, but making the VM persist on the dest host failed",
libvirt.VIR_ERR_HOOK_SCRIPT_FAILED: "A synchronous hook script failed",
libvirt.VIR_ERR_INVALID_DOMAIN_SNAPSHOT: "Invalid domain snapshot",
libvirt.VIR_ERR_NO_DOMAIN_SNAPSHOT: "Domain snapshot not found",
libvirt.VIR_ERR_INVALID_STREAM: "Stream pointer not valid",
libvirt.VIR_ERR_ARGUMENT_UNSUPPORTED: "Valid API use but unsupported by the given driver",
libvirt.VIR_ERR_STORAGE_PROBE_FAILED: "Storage pool probe failed",
libvirt.VIR_ERR_STORAGE_POOL_BUILT: "Storage pool already built",
libvirt.VIR_ERR_SNAPSHOT_REVERT_RISKY: "Force was not requested for a risky domain snapshot revert",
libvirt.VIR_ERR_OPERATION_ABORTED: "Operation on a domain was canceled/aborted by user",
libvirt.VIR_ERR_AUTH_CANCELLED: "Authentication cancelled",
libvirt.VIR_ERR_NO_DOMAIN_METADATA: "The metadata is not present",
libvirt.VIR_ERR_MIGRATE_UNSAFE: "Migration is not safe",
libvirt.VIR_ERR_OVERFLOW: "Integer overflow",
libvirt.VIR_ERR_BLOCK_COPY_ACTIVE: "Action prevented by block copy job",
}
